### ISSUE TITLE
no album picture

### ISSUE THREAD

**Issue by jfdnet** [TaylorKunZhang/SubTune#1]
![Screenshot_2023-03-14-10-20-11-01_b0bcd26370e4006709721548f001e9b6.jpg](https://user-images.githubusercontent.com/1990429/224876016-3bb83529-1123-497e-a70d-2eca82391450.jpg)

**Comment by TaylorKunZhang** [comment]
Which server are you using? Can you see the album picture using the server web page?

**Comment by jfdnet** [comment]
> Which server are you using? Can you see the album picture using the server web page?

I am using Airsonic 11.0.0. It works fine on web or other client.

<img width="503" alt="Untitled (2)" src="https://user-images.githubusercontent.com/1990429/224917667-3c43161a-b653-4ca7-8e0b-c4df3944e3f0.png">
<img width="636" alt="Untitled" src="https://user-images.githubusercontent.com/1990429/224917676-804ecaaa-356e-4aab-91b3-2ae0b5481437.png">
<img width="842" alt="Untitled (1)" src="https://user-images.githubusercontent.com/1990429/224917748-834fb53b-3590-4d12-a30f-333d35d32346.png">

**Comment by TaylorKunZhang** [comment]
Please use this apk to verify that the bug is fixed or not.
[SubTune-1.1.1.apk.zip](https://github.com/TaylorKunZhang/SubTune/files/10975084/SubTune-1.1.1.apk.zip)

**Comment by jfdnet** [comment]
> Please use this apk to verify that the bug is fixed or not.
> [SubTune-1.1.1.apk.zip](https://github.com/TaylorKunZhang/SubTune/files/10975084/SubTune-1.1.1.apk.zip)

It works. Bug fixed. Tks!
