### ISSUE TITLE
感谢+建议

### ISSUE THREAD

**Issue by mixpplus** [TaylorKunZhang/SubTune#3]
非常感谢提供了这么棒的app，找了好久一直没找到合适的，直到遇见了你 ❤！
使用过程中还是发现一点点小问题的：
 1. 服务器地址加上协议无法连接，不知道是不是所有人都这样
 2. 如果可以加上动态歌词就更好了（这个不着急，现在也能用）
 3. 再次感谢

**Comment by TaylorKunZhang** [comment]
感谢你的支持

问题1：目前的设计是这样的，服务器地址只写域名，默认协议是 http，如果勾选 https 则是 https。如果服务器地址中也输入了协议，就会造成协议重复，无法连接。这样确实可能对用户造成不便，下一版我调整一下，优先使用服务器地址中的协议。

问题2：动态歌词我也想做，但是 Subsonic API 歌词接口拿到的歌词是去除了时间点，无法实现动态歌词。Navidrome web 支持动态歌词，但 Navidrome 使用的是自己的内部接口，不是 Subsonic API。
