### ISSUE TITLE
No covers or playback with Navidrome.

### ISSUE THREAD

**Issue by Mihara** [TaylorKunZhang/SubTune#4]
Version 1.1.1, I've been able to connect it to my [Navidrome](https://www.navidrome.org/) 0.49.3 instance.

While I can see the full contents of my library, I neither see any cover images nor can play anything -- it just rotates a spinner, but playback never starts.

**Comment by Me0wzz** [comment]
I cannot reproduce it. I am using Navidrome v0.49.3 and SubTune v1.1.1. Music playback and loading album art work flawlessly on SubTune.

**Comment by Mihara** [comment]
Is your server in site root, though? Because mine isn't.

**Comment by TaylorKunZhang** [comment]
Please use this apk to verify that the bug is fixed or not.
[SubTune-1.1.2.apk.zip](https://github.com/TaylorKunZhang/SubTune/files/10991042/SubTune-1.1.2.apk.zip)

**Comment by Mihara** [comment]
Yes, this fixes it, everything is working now.

Thanks! :+1:
