### ISSUE TITLE
[feature request] Connecting to Nextcloud music fails ("Force plain password authentication" needed)

### ISSUE THREAD

**Issue by konwin** [TaylorKunZhang/SubTune#5]
Hello,
I tried to use your app with the integrated Nextcloud subsonic server. I created an API-key on the Nextcloud interface which gives me an username and password. When using this with SubTune I get an "Token authentication not supported for LDAP users." error.
~~What does that mean? I can't make any sense out of this message?! I'm not using LDAP in any way!~~
edit: I found out that the [Token authentication is somehow not implemented in Nextcloud music](https://github.com/owncloud/music/issues/893) and an option "Force plain password authentication" is needed for clients to connect. Maybe you will consider adding this option to your app?!
![image](https://user-images.githubusercontent.com/44242369/225881287-95e34b6a-fdc2-425f-bcdf-e16170a3479c.png)

**Comment by TaylorKunZhang** [comment]
Thanks for the feedback. This request will be implemented in the next version, SubTune 1.2.0.
