### ISSUE TITLE
Can't play

### ISSUE THREAD

**Issue by jfdnet** [TaylorKunZhang/SubTune#6]
Can't play on 1.1.1 / 1.1.2 / 1.2

<img width="636" alt="224917676-804ecaaa-356e-4aab-91b3-2ae0b5481437" src="https://user-images.githubusercontent.com/1990429/226149453-1d07d927-99c0-45bd-af4a-dc6c5fa945e3.png">

**Comment by TaylorKunZhang** [comment]
I am using the same version of Airsonic and it is working.
<img width="473" alt="airsonic" src="https://user-images.githubusercontent.com/15033489/226253450-a5cb8fc5-f7c2-4b3c-a4a8-18eb20411d9c.png">

**Comment by jfdnet** [comment]
> I am using the same version of Airsonic and it is working. <img alt="airsonic" width="473" src="https://user-images.githubusercontent.com/15033489/226253450-a5cb8fc5-f7c2-4b3c-a4a8-18eb20411d9c.png">

今天把后端从 Airsonic-advance 换用成 Navidrome 之后，一切都很完美，顺利播放。谢谢 🙏
