### ISSUE TITLE
[Feature request] Queue random songs

### ISSUE THREAD

**Issue by TheSunCat** [TaylorKunZhang/SubTune#8]
When listening to music on Funkwhale, it is nice to be able to go to the "radios" section and select one, such as Random, and listen to everything on my library. I'm not familiar with the Subsonic protocol, but would a similar feature be possible to have on SubTune?
Thanks!

**Comment by TaylorKunZhang** [comment]
Do you mean to add the feature of randomly playing all songs on SubTune? Subsonic supports getting random songs, but only supports a maximum of 500 songs.

**Comment by TaylorKunZhang** [comment]
Thanks for the feedback. This request will be implemented in the next version, SubTune 1.3.0.
